### ISSUE TITLE
Connection to LE devices 

### ISSUE THREAD

**Issue by Nikita-Presnov** [Sash0k/bluetooth-spp-terminal#11]
Not available connection to le devices, I need in for JDY-23.

Нет соеденения с le устройствами, ктороые нельзя подключить, можно только общатся.

**Comment by Sash0k** [comment]
все верно, такой функционал я не предусматривал

**Comment by Nikita-Presnov** [comment]
А будет?

**Comment by Sash0k** [comment]
у меня в этом нет потребности прямо сейчас.
но я не буду возражать против патча с таким функционалом, либо мое время можно купить (технически понятно как делать)

**Comment by Sash0k** [comment]
возможно позже, и уже в версии для Авроры
