### ISSUE TITLE
Styles.xml error

### ISSUE THREAD

**Issue by ianchung** [Sash0k/bluetooth-spp-terminal#2]
Dear admin,
 I import this project and it show error in styles.xml: Error retrieving parent for item: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock'. 

How could I fix it ? Thank you very much.

**Comment by alirezamghm** [comment]
@ianchung i have this problem 

you fix it?

**Comment by Sash0k** [comment]
ActionBarSherlock is now deprecated
