### ISSUE TITLE
Gradle 'bluetooth-spp-terminal-master' project refresh failed

### ISSUE THREAD

**Issue by phillip-toone** [Sash0k/bluetooth-spp-terminal#4]
Please excuse my inexperience with Android development but I get the following error:

Error:Could not find com.android.tools.build:gradle:2.2.0.
Searched in the following locations:
    file:/opt/android-studio/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    file:/opt/android-studio/gradle/m2repository/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.2.0/gradle-2.2.0.jar
Required by:
    :bluetooth-spp-terminal-master:unspecified

**Comment by Sash0k** [comment]
ced61d3
