### ISSUE TITLE
Feature request: limit log size

### ISSUE THREAD

**Issue by Peque** [Sash0k/bluetooth-spp-terminal#5]
Right now the log/history seems to have no limit. This way, if messages are received very fast, or if we keep the device receiving data for a long time, the application starts to be slow when updating the log/history with new values.

It would be great to have an option in "Settings" to set a maximum log size. This way, when new data is received old data is deleted if the max log size has been reached.

Maybe the size could be set in lines, rather than actual bytes.

**Comment by Sash0k** [comment]
запилил в версии 1.2 (см. ced61d3)
